"""refactor: moves to cud model for object lifecycle

Revision ID: 07fbd5c2d677
Revises: 36c6f9571c8c
Create Date: 2023-05-18 00:44:03.777553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fbd5c2d677'
down_revision = '36c6f9571c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_file_metadata', sa.Column('created_by_user_id', sa.UUID(), nullable=False))
    op.add_column('s3_file_metadata', sa.Column('last_updated_by_user_id', sa.UUID(), nullable=False))
    op.add_column('s3_file_metadata', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.drop_constraint('s3_file_metadata_user_id_fkey', 's3_file_metadata', type_='foreignkey')
    op.create_foreign_key(None, 's3_file_metadata', 'user', ['deleted_by_user_id'], ['id'])
    op.create_foreign_key(None, 's3_file_metadata', 'user', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 's3_file_metadata', 'user', ['last_updated_by_user_id'], ['id'])
    op.drop_column('s3_file_metadata', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_file_metadata', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 's3_file_metadata', type_='foreignkey')
    op.drop_constraint(None, 's3_file_metadata', type_='foreignkey')
    op.drop_constraint(None, 's3_file_metadata', type_='foreignkey')
    op.create_foreign_key('s3_file_metadata_user_id_fkey', 's3_file_metadata', 'user', ['user_id'], ['id'])
    op.drop_column('s3_file_metadata', 'deleted_by_user_id')
    op.drop_column('s3_file_metadata', 'last_updated_by_user_id')
    op.drop_column('s3_file_metadata', 'created_by_user_id')
    # ### end Alembic commands ###
