"""adds reset token fields

Revision ID: 36c6f9571c8c
Revises: bcc325226a11
Create Date: 2023-05-07 05:41:22.548083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c6f9571c8c'
down_revision = 'bcc325226a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token_expiry')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
