"""adds otp fields

Revision ID: 64e03973ea0f
Revises: c077dbfdeb0c
Create Date: 2022-07-18 22:55:17.333073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e03973ea0f'
down_revision = 'c077dbfdeb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('otp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    op.drop_column('user', 'mobile_number')
    # ### end Alembic commands ###
