"""drops required constraint of prefix

Revision ID: 6b3a877ee8e4
Revises: d8fb062b42d6
Create Date: 2023-04-18 01:24:48.681012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3a877ee8e4'
down_revision = 'd8fb062b42d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s3_file_metadata', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s3_file_metadata', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
