"""changes optionality of various fields

Revision ID: 7fd060beb5c7
Revises: 818ec6ee5829
Create Date: 2023-05-01 05:43:43.378723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fd060beb5c7'
down_revision = '818ec6ee5829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'verification_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'verification_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
