"""adds verification token

Revision ID: 818ec6ee5829
Revises: 6b3a877ee8e4
Create Date: 2023-05-01 05:37:20.368602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818ec6ee5829'
down_revision = '6b3a877ee8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_token', sa.String(), nullable=False))
    op.add_column('user', sa.Column('verification_token_expiry', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token_expiry')
    op.drop_column('user', 'verification_token')
    # ### end Alembic commands ###
