"""adds s3 meta

Revision ID: b9edd612a408
Revises: 64e03973ea0f
Create Date: 2022-07-21 03:23:36.883654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9edd612a408'
down_revision = '64e03973ea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
