"""change password field name

Revision ID: c4cbcb7020fa
Revises: f924d213939c
Create Date: 2022-07-21 09:54:17.789809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cbcb7020fa'
down_revision = 'f924d213939c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
