"""changes for s3 file meta

Revision ID: d8fb062b42d6
Revises: c4cbcb7020fa
Create Date: 2023-04-18 00:06:49.492469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fb062b42d6'
down_revision = 'c4cbcb7020fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_file_metadata', sa.Column('is_valid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3_file_metadata', 'is_valid')
    # ### end Alembic commands ###
